### Tensors
It is a multi-dimensional matrix containing elements o a single data type

In [1]:
import torch

In [6]:
# torch.empty(size): uninitialised
x = torch.empty(5, 3) # 5x3 matrix
print(x)
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector
print(x)
x = torch.empty(4,3,2) # 3D tensor
print(x)

tensor([[8.9966e-20, 0.0000e+00, 8.9545e-20],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 9.1084e-44]])
tensor([8.9297e-20])
tensor([8.9274e-20, 0.0000e+00, 8.9715e-20])
tensor([[[8.9273e-20, 0.0000e+00],
         [8.9537e-20, 0.0000e+00],
         [4.4842e-43, 0.0000e+00]],

        [[1.5695e-43, 0.0000e+00],
         [8.9541e-20, 0.0000e+00],
         [2.2194e-28, 4.5818e-41]],

        [[0.0000e+00, 0.0000e+00],
         [1.1351e-43, 0.0000e+00],
         [8.9275e-20, 0.0000e+00]],

        [[8.9391e-20, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])


In [9]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

# torch.zeros(size), torch.ones(size): zeros and ones
x = torch.zeros(5, 3)
print(x)
# torch.ones 
x = torch.ones(5, 3)
print(x)

tensor([[0.0224, 0.8974, 0.9190],
        [0.3079, 0.3431, 0.6771],
        [0.0530, 0.4458, 0.0414],
        [0.7971, 0.0981, 0.4272],
        [0.4812, 0.7815, 0.2912]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
