### Tensors
It is a multi-dimensional matrix containing elements o a single data type

In [1]:
import torch

In [6]:
# torch.empty(size): uninitialised
x = torch.empty(5, 3) # 5x3 matrix
print(x)
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector
print(x)
x = torch.empty(4,3,2) # 3D tensor
print(x)

tensor([[8.9966e-20, 0.0000e+00, 8.9545e-20],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 9.1084e-44]])
tensor([8.9297e-20])
tensor([8.9274e-20, 0.0000e+00, 8.9715e-20])
tensor([[[8.9273e-20, 0.0000e+00],
         [8.9537e-20, 0.0000e+00],
         [4.4842e-43, 0.0000e+00]],

        [[1.5695e-43, 0.0000e+00],
         [8.9541e-20, 0.0000e+00],
         [2.2194e-28, 4.5818e-41]],

        [[0.0000e+00, 0.0000e+00],
         [1.1351e-43, 0.0000e+00],
         [8.9275e-20, 0.0000e+00]],

        [[8.9391e-20, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])


In [9]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

# torch.zeros(size), torch.ones(size): zeros and ones
x = torch.zeros(5, 3)
print(x)
# torch.ones 
x = torch.ones(5, 3)
print(x)

tensor([[0.0224, 0.8974, 0.9190],
        [0.3079, 0.3431, 0.6771],
        [0.0530, 0.4458, 0.0414],
        [0.7971, 0.0981, 0.4272],
        [0.4812, 0.7815, 0.2912]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
# check size of a tensor
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [15]:
# check data type
print(x.dtype)

# specify data type
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)
print(x.dtype)

torch.int64
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [16]:
# construct from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [ ]:
# require gradient argument
x = torch.tensor([5.5, 3], requires_grad=True) # used in variable in our model that we want to optimize
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [23]:
# Tensor operations
x = torch.ones(2,2)
y = torch.rand(2,2)
print(y)
print(x)
# elementwise addition
z = x + y 
print(z)
# same as
z = torch.add(x, y)
print(z)

# subtraction
z = x - y
print(z)
# same as
z = torch.sub(x, y)
print(z)

# multiplication
z = x * y
print(z)
# same as       
z = torch.mul(x, y)
print(z)

# division
z = x / y
print(z)
# same as
z = torch.div(x, y)
print(z)





tensor([[0.0118, 0.4990],
        [0.3886, 0.8521]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1.0118, 1.4990],
        [1.3886, 1.8521]])
tensor([[1.0118, 1.4990],
        [1.3886, 1.8521]])
tensor([[0.9882, 0.5010],
        [0.6114, 0.1479]])
tensor([[0.9882, 0.5010],
        [0.6114, 0.1479]])
tensor([[0.0118, 0.4990],
        [0.3886, 0.8521]])
tensor([[0.0118, 0.4990],
        [0.3886, 0.8521]])
tensor([[84.4064,  2.0039],
        [ 2.5731,  1.1736]])
tensor([[84.4064,  2.0039],
        [ 2.5731,  1.1736]])


In [26]:
# slicing
x = torch.rand(5, 3)
print(x)
print(x[:,0]) # all rows, first column
print(x[1,:]) # second row, all columns
print(x[1,1]) # second row, second column

# get the actual value if only 1 element in your tensor
print(x[1,1].item())


tensor([[0.2667, 0.3737, 0.5274],
        [0.2510, 0.4133, 0.6010],
        [0.9073, 0.1101, 0.9990],
        [0.6984, 0.8299, 0.1587],
        [0.9481, 0.2942, 0.7282]])
tensor([0.2667, 0.2510, 0.9073, 0.6984, 0.9481])
tensor([0.2510, 0.4133, 0.6010])
tensor(0.4133)
0.4133215546607971


In [29]:
# Reshape tensors
x = torch.randn(4, 4)
y = x.view(16)
print(x)
print(y)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

tensor([[-0.8942,  0.8141,  1.4923, -0.5768],
        [ 2.2542,  0.2854, -1.8399, -0.4064],
        [ 0.2678,  0.2603, -0.3936, -0.4922],
        [ 0.7454, -1.0995,  0.7310, -0.9470]])
tensor([-0.8942,  0.8141,  1.4923, -0.5768,  2.2542,  0.2854, -1.8399, -0.4064,
         0.2678,  0.2603, -0.3936, -0.4922,  0.7454, -1.0995,  0.7310, -0.9470])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
