### Tensors
It is a multi-dimensional matrix containing elements o a single data type

In [1]:
import torch

In [6]:
# torch.empty(size): uninitialised
x = torch.empty(5, 3) # 5x3 matrix
print(x)
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector
print(x)
x = torch.empty(4,3,2) # 3D tensor
print(x)

tensor([[8.9966e-20, 0.0000e+00, 8.9545e-20],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 9.1084e-44]])
tensor([8.9297e-20])
tensor([8.9274e-20, 0.0000e+00, 8.9715e-20])
tensor([[[8.9273e-20, 0.0000e+00],
         [8.9537e-20, 0.0000e+00],
         [4.4842e-43, 0.0000e+00]],

        [[1.5695e-43, 0.0000e+00],
         [8.9541e-20, 0.0000e+00],
         [2.2194e-28, 4.5818e-41]],

        [[0.0000e+00, 0.0000e+00],
         [1.1351e-43, 0.0000e+00],
         [8.9275e-20, 0.0000e+00]],

        [[8.9391e-20, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])


In [9]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

# torch.zeros(size), torch.ones(size): zeros and ones
x = torch.zeros(5, 3)
print(x)
# torch.ones 
x = torch.ones(5, 3)
print(x)

tensor([[0.0224, 0.8974, 0.9190],
        [0.3079, 0.3431, 0.6771],
        [0.0530, 0.4458, 0.0414],
        [0.7971, 0.0981, 0.4272],
        [0.4812, 0.7815, 0.2912]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
# check size of a tensor
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [15]:
# check data type
print(x.dtype)

# specify data type
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)
print(x.dtype)

torch.int64
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [16]:
# construct from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [ ]:
# require gradient argument
x = torch.tensor([5.5, 3], requires_grad=True) # used in variable in our model that we want to optimize
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [23]:
# Tensor operations
x = torch.ones(2,2)
y = torch.rand(2,2)
print(y)
print(x)
# elementwise addition
z = x + y 
print(z)
# same as
z = torch.add(x, y)
print(z)

# subtraction
z = x - y
print(z)
# same as
z = torch.sub(x, y)
print(z)

# multiplication
z = x * y
print(z)
# same as       
z = torch.mul(x, y)
print(z)

# division
z = x / y
print(z)
# same as
z = torch.div(x, y)
print(z)





tensor([[0.0118, 0.4990],
        [0.3886, 0.8521]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1.0118, 1.4990],
        [1.3886, 1.8521]])
tensor([[1.0118, 1.4990],
        [1.3886, 1.8521]])
tensor([[0.9882, 0.5010],
        [0.6114, 0.1479]])
tensor([[0.9882, 0.5010],
        [0.6114, 0.1479]])
tensor([[0.0118, 0.4990],
        [0.3886, 0.8521]])
tensor([[0.0118, 0.4990],
        [0.3886, 0.8521]])
tensor([[84.4064,  2.0039],
        [ 2.5731,  1.1736]])
tensor([[84.4064,  2.0039],
        [ 2.5731,  1.1736]])


In [25]:
# slicing
x = torch.rand(5, 3)
print(x)
print(x[:,0]) # all rows, first column
print(x[1,:]) # second row, all columns
print(x[1,1]) # second row, second column


tensor([[0.8519, 0.2421, 0.8938],
        [0.3553, 0.1748, 0.1911],
        [0.8769, 0.9195, 0.0790],
        [0.6870, 0.4800, 0.3625],
        [0.8791, 0.9055, 0.1143]])
tensor([0.8519, 0.3553, 0.8769, 0.6870, 0.8791])
tensor([0.3553, 0.1748, 0.1911])
tensor(0.1748)
