### Tensors
In PyTorch, a Tensor is the core data structure, similar to NumPy arrays but with GPU acceleration. Tensors are used for all operations in deep learning models.

In [1]:
# Creating tensors
import torch 
tensor_a = torch.tensor([[1,2], [3,4]])
tensor_a

tensor([[1, 2],
        [3, 4]])

In [4]:
# torch methods
# Zeros tensor
zeros = torch.zeros(3,3)

# ones tensor
ones = torch.ones(2,2)

# random tensor
random_tensor = torch.rand(2,3)

# identity matrix
identity = torch.eye(3)

print(f"zeros : {zeros}, ones: {ones},\n random tensor: {random_tensor},\n identity: {identity}")

zeros : tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]), ones: tensor([[1., 1.],
        [1., 1.]]),
 random tensor: tensor([[0.0319, 0.6614, 0.8831],
        [0.8637, 0.6871, 0.3528]]),
 identity: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
# Tensor attributes
x = torch.rand(4,5)
print(f"Shape: {x.shape}")
print(f"Datatype: {x.dtype}")
print(f"Device: {x.device}")

Shape: torch.Size([4, 5])
Datatype: torch.float32
Device: cpu


In [6]:
# Operations on tensors
x = torch.tensor([1.0, 2.0,3.0])
y = torch.tensor([4.0, 5.0, 6.0])

# Element-wise addition
z = x + y
# Multiplication
z_mul = x * y

# Matrix multiplication
mat1 = torch.rand(2,3)
mat2 = torch.rand(3,2)
result = torch.matmul(mat1,mat2)

print(f"Addition: {z}\n Multiplication: {z_mul}\n Matrix Multiplication : {result}")


Addition: tensor([5., 7., 9.])
 Multiplication: tensor([ 4., 10., 18.])
 Matrix Multiplication : tensor([[1.0211, 0.6608],
        [1.3372, 0.5282]])


In [8]:
# Reshaping and slicing
x = torch.arange(9).reshape(3,3)
print(x)

print(x[0, :]) # first row
print(x[: ,1]) # second column

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 1, 2])
tensor([1, 4, 7])


In [9]:
# converting between numpy and tensors
import numpy as np

# Convert tensor to numpy
tensor = torch.tensor([1,2,4])
num_array = tensor.numpy()
print(num_array)
# Convert numpy to tensor
array = np.array([3.4,54.3, 34.3])
tensor_from_numpy = torch.from_numpy(array)

print(tensor_from_numpy)

[1 2 4]
tensor([ 3.4000, 54.3000, 34.3000], dtype=torch.float64)


In [ ]:
# Autograd for differentiation
x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 5*x 
y.backward() # compute derivative

print(x.grad) # dy/dx at x = 2


tensor(17.)
